version: "3.9"

#servisy (procesy), ktere pobezi jako containery
services:

  #nginx webserver
  nginx:
    image: nginx:stable-alpine
    #zleva port na kterem je dostupna aplikace, pokud je vychozi 5000, tak nemenit
    ports: 
        - "5000:80"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  #flask aplikace     
  web:
    #nazev slozky, ve ktere se nachazi root aplikace app.py
    build: ./flask
    command: flask run